### PR TITLE
escape HTML characters

### PR DESCRIPTION
**Pull request by lemna**
Hi Max,

this is a proposal to fix issue #40. I've added a test based on the example in the issue; it passes all existing tests as well.

/Peter.

### CODE REVIEW

**Comment by gforge** [comment]
Thanks! Awesome work as always, would you like to be an official co-author? Seems silly that I check your work.

**Comment by gforge** [comment]
Hey Peter, I added you as a package co-author. Are you OK with that? Also, have you considered if you want to have co-maintainer status of this repo?

**Comment by lemna** [comment]
Hi Max, 
sorry for the very late answer but I've been ill. I'd be happy to help out with maintaining the repo.
/Peter

**Comment by gforge** [comment]
Awesome, I've added you as a collaborator! I think you're pretty familiar with the package style but if there is anything that you wonder about let me know. /Max

**Pull request merged**
